[package]
name = "watch_and_move"
version = "0.1.0"
authors = ["geunyeong <geunyeong@molocoads.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify = "4.0.15"
fs_extra = "1.2.0"
